const CACHE_NAME = 'jessica-nigri-2048-v1';
const urlsToCache = [
  'jessica-nigri-edition-8.html',
  './images/tile-2.jpg',
  './images/tile-4.jpg', // Make sure to use the correct extensions (.jpg or .gif)
  './images/tile-8.gif',
  './images/tile-16.gif',
  './images/tile-32.gif',
  './images/tile-64.gif',
  './images/tile-128.gif',
  './images/tile-256.gif',
  './images/tile-512.gif',
  './images/tile-1024.jpg',
  './images/tile-2048.jpg',
  './images/icon-192.png', // Add your icon paths
  './images/icon-512.png', // Add your icon paths
  // You might also need to cache these if they are essential and local:
  // './2048_ Jessica Nigri Edition_files/main.css',
  // './2048_ Jessica Nigri Edition_files/jquery.min.js.download',
  // './2048_ Jessica Nigri Edition_files/wrapper.js.download',
  // './2048_ Jessica Nigri Edition_files/wrapper.css'
];

// Note: The files listed with ".download" or from the "_files" subfolder
// are likely generated by Chrome's "Save Page As". For true portability,
// you'd ideally download those original assets and place them in your
// main game folder or a dedicated "js" or "css" subfolder, then update
// the HTML links to point to these new local paths.
// For now, let's focus on the images and the main HTML.

self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then(cache => {
        console.log('Opened cache');
        return cache.addAll(urlsToCache);
      })
  );
});

self.addEventListener('fetch', event => {
  event.respondWith(
    caches.match(event.request)
      .then(response => {
        // Cache hit - return response
        if (response) {
          return response;
        }
        return fetch(event.request);
      })
  );
});

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys().then(cacheNames => {
      return Promise.all(
        cacheNames.map(cacheName => {
          if (cacheName !== CACHE_NAME) {
            return caches.delete(cacheName);
          }
        })
      );
    })
  );
});